### ISSUE TITLE
Return tasks sorted by id when performing GET /api/task

### ISSUE THREAD

**Issue by b0gdanp3trovic** [Shigoto-Q/shigoto#98]
Or do this on frontend instead?

**Comment by SimeonAleksov** [comment]
default ordering is by id,  no need

**Comment by SimeonAleksov** [comment]
Branch [issue-98-Return_tasks_sorted_by_id_when_performing_GET_/api/task](https://github.com/Shigoto-Q/shigoto/tree/issue-98-Return_tasks_sorted_by_id_when_performing_GET_/api/task) created!
